# Generated by Django 5.0.6 on 2024-08-14 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=80)),
                ('contact_subject', models.CharField(max_length=150)),
                ('contact_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hotels/images/')),
                ('rooms', models.CharField(max_length=20)),
                ('average_ratings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adult', models.IntegerField(default=0)),
                ('child', models.IntegerField(default=0)),
                ('special_req', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('images', models.ImageField(upload_to='hotels/images/rooms/')),
                ('description', models.TextField()),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bathroom', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('child_facility', models.BooleanField(default=False)),
                ('child_no', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotels.hotel')),
            ],
        ),
    ]
